### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by erasche** [erasche/gxargparse#4]
```
Traceback (most recent call last):
  File "cpt_shinefind.py", line 24, in <module>
    parser.add_argument('--lookahead_min', action='store_const', help='Number of bases upstream of CDSs to end search', default=5)
  File "/home/users/cpt/cpt/esr/Projects/cpt/dev/software/python-galaxy-tools/.venv/local/lib/python2.7/site-packages/argparse/__init__.py", line 44, in add_argument
    result = self.parser.add_argument(*args, **kwargs)
  File "/usr/lib/python2.7/argparse.py", line 1283, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() takes at least 4 arguments (5 given)
```

**Comment by erasche** [comment]
`action='store_const'` wants a `const=###` specified. Not a bug
